config/routes.rb
Rails.application.routes.draw do

  root 'homepage#index'

  get 'index'         => 'homepage#index'
  get 'restore'       => 'homepage#restore', as: :restore
  get 'service'       => 'homepage#service', as: :service
  get 'swatch'        => 'homepage#swatch',  as: :swatch
  get 'shop'          => 'homepage#shop'  ,  as: :shop
  get 'contact'       => 'homepage#contact', as: :contact
  post 'contact_email' => 'homepage#contact_email'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
  def restore
  end
  def service
  end
  def swatch
  end
  def shop
  end
  def contact
  end
  def contact_email
    redirect_to contact_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/homepage/contact.html.erb
<div id="contact_us">
  <div class="contact_nums">
    <div class="col-xs-6"><%= image_tag 'visit_us.png' %></div>
    <div class="col-xs-6"><%= image_tag 'visit_us_2.png' %></div>
  </div>
  <div class="two_column">
    <div id="visit_us">
      <ul>
        <li><div id="visit_head"><%= image_tag 'point.png' %> Miracoli Furniture, Inc</div> </li>
        <li> 1026 E.Lacy Ave.</li>
        <li> Anaheim, CA 92805</li>
        </br>
        <li> miracolifurniture@yahoo.com</li>
        </br>
        <li>Office: (714) 502-9214</li>
        <li>Fax: (714) 502-9120</li>
        </br>
        <li><div id="visit_head2">Our Hours Are:</div></li>
        </br>
        <li>Monday-Friday</li>
        <li>From 8:00am - 4:00p.m.</li>
        </br></br>
        <li>For updates, follow us on Social Media:</li>
        </br>
        <li><%= image_tag 'fb.png' %>  <%= image_tag 'insta.png' %></li>
      </ul>
    </div>
    <div id="request_prop">
      <%= form_tag '/contact_email', multipart: true do -%>
          <div><%= label_tag 'name',nil,class: "contact_input"  %></div>
          <div><%= text_field_tag 'Name','',class: "contact_size" %></div>
          </br>
          <div><%= label_tag 'Phone',nil,class: "contact_input"  %></div>
          <div><%= phone_field_tag 'Phone','',class: "contact_size" %></div>
          </br>
          <div><%= label_tag 'email',nil,class: "contact_input"  %></div>
          <div><%= email_field_tag 'email','',class: "contact_size"%></div>
          </br>
          <div><%= label_tag 'furniture',nil,class: "contact_input"  %></div>
          <div><%= text_area_tag 'furniture','',class: "contact_tsize" %></div>
          </br>
          <div><%= label_tag 'services',nil,class: "contact_input" %></div>
          <div><%= text_area_tag 'services', '',class: "contact_tsize" %></div>
          <div id="theme"><%= label_tag 'theme', 'Pick Up or Delivery? (Optional):',class: "contact_input" %>
          <% [ 'Yes Please!', 'NO', 'Pick-Up', 'Delivery Only'].each do |theme| %>
              <br><%= radio_button_tag 'theme', theme, theme %>
              <%= theme.humanize %>
          <% end %>
          </div>
          </br>
          <div><%= label_tag 'contact_attach', 'Upload Attachments:'%></div>
          <div class="upload"><%= file_field_tag 'contact_attach[]', multiple: true %></div>
          <br>
          <div><%= submit_tag 'Submit',class: 'melbtn' %></div>
          <div>You will be contacted within 1 business day.</div>
      <% end -%>
    </div>
  </div>
</div>

app/views/homepage/index.html.erb
<div id="index">
  <div id="owl-carousel">
    <div class='item'> <%= image_tag 'Banner_1.jpg' %> </div>
    <div class='item'> <%= image_tag 'Banner_2.jpg' %> </div>
    <div class='item'> <%= image_tag 'Banner_3.jpg' %> </div>
  </div>

  <div id="about_us" class="container">
    <center><h1>About Us</h1></center>
    <div class="row">
      <div class="introduction1 col-md-5 col-md-offset-1">
        <p>
        Miracoli Furniture, Inc. is a family owned and operated business.
        <br>
        We are committed to bringing you into our family by offering you the best prices,
        best services and the most environmental form of reupholstering your patio furniture.
        We have over 29 years of experience in the manufacturing of aluminum outdoor furniture,
        providing us with a strong foundation in the techniques needed for customizing the
        restoration of your outdoor furniture.
        </br></br>
        Our services include re-sling, re-strapping, sandblast & powdercoat,
        welding as well as the manufacture of umbrella covers, cushions and parts.
        Our refinishing processes can restore and customize your outdoor furniture to look new again.
        </p>
      </div>
      <div class="col-md-5">
        <p>When you contact us, you will be assured to always speak to a representative that will
        answer all your questions and concerns. By working on a case-to-case basis,
        we commit to making your <br>experience effortless.
        </br></br>
        You are welcome to call, e-mail, and or request a proposal at any time. Because your
        inquiry is important to us, we commit to contacting you within 1 business day, if not immediately.
        </br></br>
        We service residential areas, homeowners associations, hotels and even cruise ships
        in all of the Southern California region—from San Luis Obispo to San Diego.
        Out of state work orders are upon special request.</p>
      </div>
    </div>
  </div>

  <div>
    <center><h1>Why Restore?</h1></center>
  </div>

  <div id="why_restore">
    <div class="container">
      <div class="row">

        <div class="restore1 col-xs-5 col-xs-offset-1">
          <ul>
            <li><%= image_tag 'go_green.png' %>&nbsp;&nbsp;Go Green!</li>
            <li><%= image_tag 'customize.png' %>&nbsp;&nbsp;Customize Your Furniture</li>
            <li><%= image_tag 'services.png' %>&nbsp;&nbsp; Best Customer Service</li>
          </ul>
        </div>

        <div class="restore2 col-xs-5">
          <ul>
            <li><%= image_tag 'savings.png' %>&nbsp;&nbsp; Savings</li>
            <li><%= image_tag 'repairs.png' %>&nbsp;&nbsp; Case-To-Case Repairs</li>
            <li><%= image_tag 'delivery.png' %>&nbsp;&nbsp;Pick-UP & Delivery Services</li>
          </ul>
        </div>
      </div>

    </div>
  </div>

  <div id="our_services">
    <center><h1>Our Services</h1></center>
    </br>
    <center>
        <ul class="list-inline" id="service_list">
          <li>
            <ul id="sub_list">
              <li>
                <%= image_tag 're-sling.png' %>
              </li><!-- 
              --><li>
                Re-Sling
              </li>
            </ul>
          </li><!-- 

          --><li>
            <ul id="sub_list">
              <li>
                <%= image_tag 'cushion.png' %>
              </li><!-- 
              --><li>
                Cushion
              </li>
            </ul>
          </li><!-- 

          --><li>
            <ul id="sub_list">
              <li>
                <%= image_tag 'strip_n_powdercoat.png' %>
              </li><!-- 
          --><li>
                Strip and Powercoat
              </li>
            </ul>
          </li><!-- 

          --><li>
            <ul id="sub_list">
              <li>
                <%= image_tag 're-strap.png' %>
              </li><!-- 
           --><li>
                Re-Strap
              </li>
            </ul>
          </li>
          <li>
            <%= link_to 'MORE >>', service_path, id: "service_link" %>
          </li>
        </ul>
      </center>
  </div>

</div>

<script>
    $(document).ready(function() {

        $("#owl-carousel").owlCarousel({
            autoPlay: 3000, //Set AutoPlay to 3 seconds
            items : 1,
            itemsDesktop : [1199,1],
            itemsMobile : [479,1],
            autoHeight: true
        });
    });
</script>

app/views/homepage/restore.html.erb
<div id="restore">
  <div class="container">

    <div class="row"> 
      <span class="subheader">Why<br>Restore?</span>
    </div>

    <div class="row">
        <%= image_tag "go_green_2.png", class: "align-left"%>
          <p>GO GREEN!</p>
          Help the environment by recycling, choosing a
          </br>
          company that uses GREEN tactics, and contributing,
          </br>
          to less pounds of landfield a year.
    </div>

    <div class="row">
        <%= image_tag "savings_2.png", class: "align-right"%>
        <p>SAVINGS</p>
        Save anywhere from 30-70% than if you bought new.
    </div>

    <div class="row">
      Hello
    </div>

    <div class="row">
      Hello
    </div>

  </div>
</div>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
    <div class="row">
      <div id="fimage" class="col-xs-3">
          <%= image_tag 'logo_footer.png' %>
      </div>
      
      <div id="fmenu" class="col-xs-3">
        <span class="subtopic">Menu</span>
        </br>
        </br>
        <%= link_to "Home", root_path %>
        <br>
        <%= link_to "Why Restore?", restore_path %>
        <br>
        <%= link_to "Swatch Book", swatch_path %>
        <br>
        <%= link_to "Shop", shop_path %>
        <br>
        <%= link_to "Contact Us", contact_path %>
      </div>
      
      <div id="fcontact" class="col-xs-3">
        <span class="subtopic">Contact Us</span>
        </br>
        </br>
        1026 E.Lacy Ave., Anaheim,
        <br>
        CA 92805
        </br>
        </br>
        Office: (714) 502-9214
        <br>
        Fax: (714)502-9120
        </br>
        </br>
        info@miracolifurniture.net
        <br>
        miracolifurniture@yahoo.com
        </br>
        </br>
        Nazario Arroyo
        <br>
        Cell: (714) 651-2544
        </br>
        </br>
        Our Hours Are:
        <br>
        Monday-Friday
        <br>
        From 8:00am - 4:00p.m. Pacific Time
        <br>
        Saturday upon request
      </div>
      
      <div id="fsocial" class="col-xs-3">
        <span class="subtopic">Social</span>
        </br>
        </br>
        <%= link_to "http://www.facebook.com/", :target => "_blank" do %>
          <%= image_tag 'fb_footer.png' %>&nbsp;&nbsp;Facebook
        <% end %>
        </br>
        </br>
        <%= link_to "http://www.instagram.com", :target => "_blank" do %>
          <%= image_tag 'insta_footer.png' %>&nbsp;&nbsp;Instagram
        <% end %>
        </br>
        </br>
        <%= mail_to "me@domain.com" do %>
          <%= image_tag 'email_footer.png' %>&nbsp;&nbsp;Email
        <% end %>
      </div>
        
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div id="header">
  <div class="container">
    <%= image_tag 'logo.png' %>
    <ul class="list-inline">
      <li>
        <%= link_to "HOME", root_path %>
      </li>
      <li>|</li>
      <li>
        <%= link_to "WHY RESTORE?", restore_path %>
      </li>
      <li>|</li>
      <li>
        <%= link_to "SERVICES", service_path %>
      </li>
      <li>|</li>
      <li>
        <%= link_to "SWATCH BOOK", swatch_path %>
      </li>
      <li>|</li>
      <li>
        <%= link_to "SHOP", shop_path %>
      </li>
      <li>|</li>
      <li>
        <%= link_to "CONTACT US", contact_path %>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Miracoli</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: "/layouts/header" %>
<%= yield %>
<%= render partial: "/layouts/footer" %>

</body>
</html>